version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: wallet-postgres
    restart: always
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_admin
      POSTGRES_PASSWORD: wallet_pass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
