server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: wallet_admin
    password: wallet_pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:dev-only-secret-change-me-please-32-bytes-minimum-0000}
  expiration: 86400000
